In [1]:
x = [2, 4, 5]
y = [10, 4, 2]
print(x+y)

[2, 4, 5, 10, 4, 2]


In [7]:
import numpy as np
x_np = np.array(x)
y_np = np.array(y)
print(x)
print(type(x_np))
print(x_np + y_np)
print(x_np * 3)
print(y_np ** 2)

[2, 4, 5]
<class 'numpy.ndarray'>
[12  8  7]
[ 6 12 15]
[100  16   4]


In [16]:
salary = np.array([46, 42, 65, 70, 48, 78])
print((salary >= 50)&(salary <= 70))
print(salary[(salary >= 50)&(salary <= 70)])

[False False  True  True False False]
[65 70]


In [25]:
A = np.array([[3, 7, 15],[8, 9, 16]])
print(A)
print(A.shape)
print(A.ndim)
print(A.size)
print(A[1][0])
print(A[1,0])
print(A[:,1])

[[ 3  7 15]
 [ 8  9 16]]
(2, 3)
2
6
8
8
[7 9]
